imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
parameters:
    locale: en
framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
jms_serializer:
    enable_short_alias: false
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
nelmio_api_doc: ~